### ISSUE TITLE
how to apply looping in geoinferencing?

### ISSUE THREAD

**Issue by Rahulvks** [mhermans/mstls#1]
Hi @mhermans ,

```
import json
from shapely import shape, Point

# load GeoJSON file containing sectors
with ('sectors.json', 'r') as f:
    js = json.load(f)

# construct point based on lat/long returned by geocoder
point = Point(45.4519896, -122.7924463)

# check each polygon to see if it contains the point
for feature in js['features']:
    polygon = shape(feature['geometry'])
    if polygon.contains(point):
        print 'Found containing polygon:', feature
```

how to pass the list of point (from pandas data frame) and extract the matched polygon?

I,e I have points in the data frame 

http://archived.mhermans.net/geojson-shapely-geocoding.html

**Comment by mhermans** [comment]
Hi, thanks for you interest, but a issue on this github repository this is not the correct place to ask this type of question. 

I would recommend asking this on https://gis.stackexchange.com/, and post the link to your question here. If I have time I'll try to answer there, if not, others might do so.

**Comment by Rahulvks** [comment]
Hi  @mhermans 
The question is already asked in the StackOverflow.I looking for the answer one important task please help.

https://stackoverflow.com/questions/20776205/point-in-polygon-with-geojson-in-python

**Comment by mhermans** [comment]
No I will not help you. Please learn proper etiquette when asking help online, and stop spamming a completely unrelated Github repo of mine.
